services:
  # Backend API Service
  - type: web
    name: rag-chatbot-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
      - key: JINA_API_KEY
        sync: false
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: QDRANT_URL
        value: http://localhost:6333
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: rag_chatbot
      - key: FRONTEND_URL
        sync: false
      - key: NEWS_RSS_FEEDS
        value: "https://feeds.bbci.co.uk/news/rss.xml,https://rss.cnn.com/rss/edition.rss"
      - key: SESSION_TTL
        value: 3600
      - key: CACHE_TTL
        value: 1800

  # Frontend Static Site
  - type: web
    name: rag-chatbot-frontend
    env: static
    plan: starter
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: REACT_APP_SOCKET_URL
        sync: false
      - key: REACT_APP_APP_NAME
        value: "RAG News Chatbot"
      - key: REACT_APP_ENVIRONMENT
        value: production

databases:
  # PostgreSQL Database
  - name: rag-chatbot-db
    plan: starter
    databaseName: rag_chatbot
    user: rag_user

  # Redis Cache
  - name: rag-chatbot-redis
    plan: starter
