services:
  # Backend API Service
  - type: web
    name: rag-chatbot-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
      - key: JINA_API_KEY
        sync: false
      - key: DB_HOST
        fromDatabase:
          name: rag-chatbot-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: rag-chatbot-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: rag-chatbot-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: rag-chatbot-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: rag-chatbot-db
          property: database
      - key: REDIS_URL
        fromService:
          type: redis
          name: rag-chatbot-redis
          property: connectionString

  # Frontend Static Site
  - type: web
    name: rag-chatbot-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://rag-chatbot-backend.onrender.com/api
      - key: REACT_APP_SOCKET_URL
        value: https://rag-chatbot-backend.onrender.com
      - key: REACT_APP_APP_NAME
        value: News Chatbot
      - key: REACT_APP_ENVIRONMENT
        value: production

databases:
  # PostgreSQL Database
  - name: rag-chatbot-db
    plan: starter

  # Redis Cache
  - name: rag-chatbot-redis
    type: redis
    plan: starter
